name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake Game from commits
        uses: Platane/snk@v2
        with:
          github_user_name: LCM-DataScience
          gif_out_path: dist/github-snake.gif

      - name: Upload the generated snake game GIF
        uses: actions/upload-artifact@v2
        with:
          name: snake-game
          path: dist/github-snake.gif
