name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente
  workflow_dispatch: # Permite disparo manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake Game from commits
        uses: Platane/snk@v2
        with:
          github_user_name: LCM-DataScience
          gif_out_path: dist/github-snake.gif

      - name: Commit the Snake Game GIF
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add dist/github-snake.gif
          git commit -m "Generated Snake Game"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
